[build]
  command = "cd client && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env.production]
  [env.production.context.production.environment]
    VITE_API_URL = "https://online-counseling-platform-w4tj.onrender.com/"
    VITE_SOCKET_URL = "https://online-counseling-platform-w4tj.onrender.com/"

  [build]
  base = "client"
  command = "npm run build"
  publish = "dist"

  [build]
  publish = "dist"
  command = "npm run build"

